### ISSUE TITLE
PDFs: Rich text in comments does not transfer

### ISSUE THREAD

**Issue by adam3smith** [QualitativeDataRepository/Anno-REP#6]
See bolded "Analytic note" in https://www.dropbox.com/s/bzgh8pzsh98bykm/anno-rep-testing_paper.pdf?dl=1

**Comment by qqmyers** [comment]
FWIW: Similar issue with docx source - I've 'fixed' this there: any bold, italic, and/or hyperlinks should now appear in the annotations as written. Unfortunately, I haven't found a general mechanism to get rich text, so for these and any other styles, I'm writing custom code (if style X, then write html Y). That's not hard, but probably better to start from a whitelist of ones expected to be common (underline? font size/changes?).

Looking at pdf source after this. (Side note: I initially didn't see the issue with the example pdf because the pdf previewer in my browser didn't keep the bold either. The desktop adobe pdf viewer does.)

**Comment by qqmyers** [comment]
Should be fixed in v0.0.3 on dev now. I was able to get the xhtml version of what pdf will display in the comment which includes style (i.e.. bold) and font info. The raw source may be a little noisy, i.e. there's a dir='ltr' attribute in some places that is probably not needed, etc. If any of that breaks rendering I can remove it.

**Comment by adam3smith** [comment]
Fix confirmed, thanks!
