### ISSUE TITLE
Tables in Word don't convert to PDF

### ISSUE THREAD

**Issue by adam3smith** [QualitativeDataRepository/Anno-REP#9]
(untested so no sample, but users noted this)

**Comment by qqmyers** [comment]
This should be fixed in v0.0.3 on dev. While the conversion is just from changing to Open Office (see #4), I also realized and fixed an issue that comments in the table were not being captured correctly. (Just happened to do this in my made up test case.) It's possible that the anchors are not exactly the same as Hypothesis would create - if there are issues, getting a sample doc and Hypothesis created annotation would be helpful in fixing it. (The big question is whether Hypothesis inserts any chars in the stream to represent the table elements or just does what I did and look for the embedded paragraph elements and just treat them as though they were paragraph elements in the doc itself.

**Comment by adam3smith** [comment]
Fix confirmed
